version: '3'
services:
  server:
    image: jetbrains/teamcity-server
    ports:
     - "8111:8111"
  agent:
    build: .
    environment:
     - SERVER_URL=http://server:8111
    depends_on:
     - server
